import React from 'react';

const Terms_Conditions = () => {
    return (
        <section className="py-16 bg-gray-50 min-h-screen">
            <div className="max-w-4xl mx-auto px-6 bg-white shadow-sm rounded-2xl p-8 md:p-12 text-gray-800">
                <h1 className="text-3xl md:text-4xl font-bold text-[#0852A1] mb-8 border-b-2 border-[#0852A1]/20 pb-4">
                    Terms & Conditions
                </h1>

                <div className="space-y-8 leading-relaxed text-sm md:text-base">
                    <p>
                        This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p>
                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011, that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <strong className="text-gray-900">theenglishraj.com</strong> (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
                    </p>
                    <p>
                        The Platform is owned by <strong className="text-gray-900">The English Raj</strong>, a company incorporated under the Companies Act, 1956, with its registered office at <strong className="text-gray-900">Village Saifabad, P.O. Tehang, Phillaur, District Jalandhar, Punjab – 144410, India</strong> (hereinafter referred to as "Platform Owner," “we,” “us,” or “our”).
                    </p>
                    <p>
                        Your use of the Platform, services, and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.
                    </p>
                    <p>
                        These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                    </p>
                    <p>
                        For the purpose of these Terms of Use, wherever the context so requires, "you", “your,” or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                    </p>

                    <div className="bg-blue-50 border-l-4 border-[#0852A1] p-6 my-8 rounded-r-xl italic font-semibold text-[#0852A1]">
                        ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
                    </div>

                    <p className="font-semibold text-lg pb-2">
                        The use of the Platform and/or availing of our Services is subject to the following Terms of Use:
                    </p>

                    <div className="space-y-8 mt-4">
                        {/* Section 1 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">1</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Accuracy of Information</h3>
                                <p>To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                            </div>
                        </div>

                        {/* Section 2 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">2</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">No Warranty</h3>
                                <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                            </div>
                        </div>

                        {/* Section 3 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">3</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">At Your Own Risk</h3>
                                <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                            </div>
                        </div>

                        {/* Section 4 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">4</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Intellectual Property</h3>
                                <p>The contents of the Platform and the Services are proprietary to us and licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The content includes, but is not limited to, the design, layout, look, and graphics.</p>
                            </div>
                        </div>

                        {/* Section 5 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">5</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Unauthorized Use</h3>
                                <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                            </div>
                        </div>

                        {/* Section 6 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">6</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Service Charges</h3>
                                <p>You agree to pay us the charges associated with availing the Services.</p>
                            </div>
                        </div>

                        {/* Section 7 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">7</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Lawful Use</h3>
                                <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or by Indian or local laws that might apply to you.</p>
                            </div>
                        </div>

                        {/* Section 8 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">8</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Third-Party Links</h3>
                                <p>You acknowledge that the website and Services may contain links to third-party websites. Upon accessing these links, you will be governed by the terms of use, privacy policy, and other policies of such third-party websites. These links are provided for your convenience to provide further information.</p>
                            </div>
                        </div>

                        {/* Section 9 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">9</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Legally Binding Contract</h3>
                                <p>You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
                            </div>
                        </div>

                        {/* Section 10 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">10</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Indemnity</h3>
                                <p>You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other Policies, or your violation of any law, rules, or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
                            </div>
                        </div>

                        {/* Section 11 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">11</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Limitation of Liability</h3>
                                <p>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation, damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or loss of other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services. However, the Platform Owner's liability will not exceed the amount paid by you for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.</p>
                            </div>
                        </div>

                        {/* Section 12 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">12</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Force Majeure</h3>
                                <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
                            </div>
                        </div>

                        {/* Section 13 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">13</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Governing Law and Jurisdiction</h3>
                                <p>These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong className="text-gray-900">Jalandhar, Punjab, India</strong>.</p>
                            </div>
                        </div>

                        {/* Section 14 */}
                        <div className="flex gap-5">
                            <span className="flex-shrink-0 w-10 h-10 rounded-xl bg-[#0852A1]/10 text-[#0852A1] flex items-center justify-center font-bold text-lg">14</span>
                            <div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Contact Information</h3>
                                <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website (<strong className="text-gray-900">support@theenglishraj.com</strong>).</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};


export default Terms_Conditions;
